version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - .:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: 'ocademy-awesome-directus-key'
      SECRET: 'ocademy-awesome-directus-secret'
      ADMIN_EMAIL: 'admin@ocademy.cc'
      ADMIN_PASSWORD: 'admin'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: true
