name: awesome-main

on:
  push:
    branches:
      - main
    paths:
      - 'awesome/database/data.db'

jobs:
  compare-dbs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SQLite
      run: sudo apt-get install sqlite3
      
    - name: Install sqldiff tool
      run: |
        wget https://www.sqlite.org/2023/sqlite-tools-linux-x86-3420000.zip
        unzip sqlite-tools-linux-x86-3420000.zip

    - name: Get target branch database
      run: |
        wget -O target_data.db https://raw.githubusercontent.com/${{ github.repository }}/main/awesome/database/data.db
      
    - name: Show database schema differences
      run: ./sqlite-tools-linux-x86-3420000/sqldiff --schema target_data.db awesome/database/data.db

    - name: Show substantial tables differences
      run: |
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table Course target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table Organization target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table User target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table Tag target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table CourseTags target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table CourseOrganizations target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table UserCourses target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table Tutorial target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table TutorialTags target_data.db awesome/database/data.db
        ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey --table UserTutorials target_data.db awesome/database/data.db

    - name: Show all differences in database
      run: ./sqlite-tools-linux-x86-3420000/sqldiff --primarykey target_data.db awesome/database/data.db

    - name: Install dependencies
      run: |
        cd awesome
        npm install

    - name: Synchronize local and cloud databases
      run: |
        cd awesome/sync
        export EMAIL=${{ secrets.EMAIL }}
        export PASSWORD=${{ secrets.PASSWORD }}
        export AWS_APPSYNC_AUTHENTICATIONTYPE=${{ secrets.AWS_APPSYNC_AUTHENTICATIONTYPE_TEST }}
        export AWS_APPSYNC_GRAPHQLENDPOINT=${{ secrets.AWS_APPSYNC_GRAPHQLENDPOINT_TEST }}
        export AWS_APPSYNC_REGION=${{ secrets.AWS_APPSYNC_REGION_TEST }}
        export AWS_COGNITO_IDENTITY_POOL_ID=${{ secrets.AWS_COGNITO_IDENTITY_POOL_ID_TEST }}
        export AWS_COGNITO_REGION=${{ secrets.AWS_COGNITO_REGION_TEST }}
        export AWS_COGNITO_SIGNUP_ATTRIBUTES=${{ secrets.AWS_COGNITO_SIGNUP_ATTRIBUTES_TEST }}
        export AWS_PROJECT_REGION=${{ secrets.AWS_PROJECT_REGION_TEST }}
        export AWS_USER_POOLS_ID=${{ secrets.AWS_USER_POOLS_ID_TEST }}
        export AWS_USER_POOLS_WEB_CLIENT_ID=${{ secrets.AWS_USER_POOLS_WEB_CLIENT_ID_TEST }}
        node index.js
